config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  
  devise_for :users

  resources :dvr_systems

  resources :shows do
  	get :record
  	post :record
  	get :delete_record
  	post :delete_record
  end

  # post '/change_recording' =>'shows#change_recording'


end

app/models/box.rb
class Box < ActiveRecord::Base
  belongs_to :dvr_system
  has_many :shows

end

app/models/dvr_system.rb
class DvrSystem < ActiveRecord::Base
  belongs_to :user
  has_many :boxes 

end

app/models/show.rb
class Show < ActiveRecord::Base
	belongs_to :box


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :dvr_system
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
  before_filter :homepage_background

	def keep_controllers
    ["home", "sessions", "registrations", "passwords"]
  end

  def homepage_background
  	if keep_controllers.include?(controller_name)
  		@page_class = "homepage"
  	end
  end

end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController

end

app/controllers/dvr_systems_controller.rb
class DvrSystemsController < ApplicationController

  def index
  	@page_class = "show_page"

  	@box_1 = Box.find_by(:box_number => 1)
  	if @box_1.shows.present?
  		@box_1_shows = @box_1.shows.where(:recording => true)
  	end
  	
  	@box_2 = Box.find_by(:box_number => 2)
  	if @box_2.shows.present?
  		@box_2_shows = @box_2.shows.where(:recording => true)
  	end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_filter :authenticate_user!

	def index
		if user_signed_in?
			redirect_to dvr_systems_url
		else
			render 'home/index'
		end
	end

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController

  respond_to :html, :js

  def index
    @shows = Show.all
    @show_dropdowns = Box.all.collect { |p| [ p.box_number, p.id ] }
    @page_class = "show_page"
  end

  def update
    @show = Show.find(params[:id])

    respond_to do |format|
      if @show.update
        format.html { redirect_to show_url }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def edit
    @show = Show.find(params[:id])
  end

  def record
    show = Show.find(params[:show_id])
    show.box_id = params[:show][:box_id]

    if show.box.box_number == 1
      record_show(box_one, show)
    elsif show.box.box_number == 2
      record_show(box_two, show)
    end
    redirect_to :back
  rescue ActionController::RedirectBackError
    redirect_to shows_path
  end

  def delete_record
    show = Show.find(params[:show_id])
    show.update_attributes(recording: false)
    show.update_attributes(box_id: nil)
    redirect_to :back
  end

  private

    def box_one
      Box.find_by(:box_number => 1)
    end

    def box_two
      Box.find_by(:box_number => 2)
    end

    def record_show(box, show)
      @overlapping_shows = box.shows.where(recording: true).where("start_time <= :show_end AND end_time >= :show_start", {show_start: show.start_time, show_end: show.end_time}).flatten.first

      if @overlapping_shows.present?
        # respond_to do |format|
        #   xhr :post, :record, format: :js
        # end
        # redirect_to action: 'index', via: :change_recording
        nil
      else
        show.update_attributes(:recording => true)
        show.save
      end
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/dvr_system_helper.rb
module DvrSystemHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/dvr_systems/_shows_list_items.html.erb
<li class="shows-list-item">
  <span class="title col-md-4"><%= show.title %></span>
  <span class="showtime col-md-4"><%= show.start_time.strftime("%I:%M%P")  %> - <%= show.end_time.strftime("%I:%M%P")  %></span>
  <span class="channel col-md-3">Channel <%= show.channel %></span>
  <%= link_to show_delete_record_path(:show_id => show.id) do %>
    <i class="fa fa-times"></i>
    <span>Cancel</span>
  <% end %>
</li>

app/views/dvr_systems/index.html.erb
<section class="my-dvr-boxes container">

  <h1 class="recordings-header">My Current Recordings</h1>
  <%= link_to "All shows", shows_url, :class => "all-shows-link"  %>

  <div class="first-box">
    <h3>DVR Box 1</h3>
    <ul class="shows-list">
      <% if @box_1_shows.present? %>
        <% @box_1_shows.order("channel ASC").each do |show| %>
          <%= render :partial => 'shows_list_items', :locals => { :show => show } %>
        <% end %>
      <% else %>
        <li class="no-shows">There aren't any shows being recorded on this box. You can start recording shows by clicking 'ALL SHOWS'</li>
      <% end %>
    </ul>
  </div>

  <div class="second-box">
    <h3>DVR Box 2</h3>
    <ul class="shows-list">
      <% if @box_2_shows.present? %>
        <% @box_2_shows.order("channel ASC").each do |show| %>
          <%= render :partial => 'shows_list_items', :locals => { :show => show } %>
        <% end %>
      <% else %>
        <li class="no-shows">There aren't any shows being recorded on this box. You can start recording shows by clicking 'ALL SHOWS'</li>
      <% end %>
    </ul>
  </div>
  
</section>

app/views/home/index.html.erb
<div class="container">
  <div>
    <button class="nav-link"><%= link_to 'Sign in', new_user_session_path %></button>
    <button class="nav-link"><%= link_to 'Sign up', new_user_registration_path %></button>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="container alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-fixed-top">
  <div class="container">
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
  <!-- <li><%#= link_to 'Edit account', edit_user_registration_path %></li> -->
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <!-- <li><%#= link_to 'Sign in', new_user_session_path, class: "nav-link" %></li> -->
  <!-- <li><%#= link_to 'Sign up', new_user_registration_path, class: "nav-link" %></li> -->
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "DVR" %></title>
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Dvr" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= yield(:layout_class) %><%= @page_class %>">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
      <main>
      <%#= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shows/_show_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        <%= @shows.first.title %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/shows/index.html.erb
<section class="container">

  <p class="back-to-openings-button">
    <%= link_to "&#8592; Back to current recordings".html_safe, dvr_systems_path %>
  </p>
  <div class="all-shows">
    <ul class="show-cards">
      <% @shows.order("channel ASC").each do |show| %>
        <li class="show col-md-4 col-md-offset-1">
          <span class="show-title"><%= show.title %></span>
          <span class="show-channel">Channel <%= show.channel %></span>
          <span class="show-time"><%= show.start_time.strftime("%I:%M%P") %> -
          <%= show.end_time.strftime("%I:%M%P") %></span>
          <span class="minutes-long"><%= (show.end_time.to_i - show.start_time.to_i)/60 %> minutes</span>
          <% if show.recording == false %>
            <div class="recording">
              <%= form_for show, :url => show_record_path(:show_id => show.id), method: :post do |f| %>
                <%= f.select :box_id, @show_dropdowns, { :include_blank => 'Select a box' }, class: "show-radio-button", id: "show_box_id_#{show.id}" %>
                <%= f.submit "Record", data: { disable_with: "Please wait.." }, :disabled => true, class: "record-button" %>
              <% end %>
            </div>
          <% else %>
            <div class="recording">
              Recording on Box <%= show.box.box_number %>
              <%= link_to "Cancel", show_delete_record_path(:show_id => show.id), data: { disable_with: "Cancelling.." }, class: "cancel-record-button" %>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>

  </div>


</section>

app/views/shows/record.js.erb
  $('#myModal').modal('toggle');